# Generated by Django 4.1.7 on 2023-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
